packages:
  - apps/*
  - packages/*
catalog:
  next: 16.0.0
  zod: ^4.1.12
  "@trpc/server": ^11.5.0
  "@trpc/client": ^11.5.0
  better-auth: ^1.3.28
  drizzle-orm: ^0.44.2
  dotenv: ^17.2.2
  tsdown: ^0.15.5
